import { Button, LoadingOverlay, Text, Title } from "@mantine/core";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";

export default function Home() {
  const { status } = useSession();
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <Title order={1}>Nomos</Title>
          <Text>Track your finances</Text>
          <div className="relative flex gap-8">
            <LoadingOverlay visible={status == "loading"} />
            <Button
              onClick={
                status == "authenticated"
                  ? () => void router.push("/dashboard")
                  : () => void signIn()
              }
            >
              {"Let's go"}
            </Button>
            {status == "authenticated" && (
              <Button onClick={() => void signOut()}>sign out</Button>
            )}
          </div>
        </div>
      </main>
    </>
  );
}
